// src/components/SearchBox.vue
<template>
  <div class="search_box">
    <img
      :src="$store.state.data.searchIcon"
      :alt="$store.state.data.searchTitle"
      class="search_icon"
    >
    <input
      type="text"
      @keyup.enter="search"
      class="form-control"
      v-model="keywords"
      :placeholder="'通过 '+ $store.state.data.searchTitle +' 来搜索'"
    >
    <button class="search_button" @click="search">搜索</button>
  </div>
</template>
<script>
export default {
  data() {
    return {
      keywords: ""
    };
  },
  methods: {
    search() {
      let searchUrl =
        this.$store.state.data.searchUrl + encodeURIComponent(this.keywords);
      location.href = searchUrl;
    }
  }
};
</script>
<style lang="less" scoped>
</style>

// src/components/newtab/SearchBox.jsx
import React from "react";
import ReactDom from "react-dom";

// 搜索框组件
class SearchBox extends React.Component {
  constructor() {
    super();
  }
  render() {
    return (
      <div class="container search_box">
        <div class="row">
          <div class="col search_bar">
            <div class="search_input mx-auto">
              <img src="images/default.png" alt="" class="search_icon" />
              <input
                type="text"
                class="form-control"
                placeholder="通过 百度 来搜索"
              />
              <button class="search_button">搜索</button>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
