// src/components/TopBar.vue
<template>
  <div class="topbar">
    <button @click="showCreate()">
      <img src="../assets/images/add.png">
      <span>新增</span>
    </button>
    <button @click="toggleEditMode()">
      <img src="../assets/images/edit.png">
      <span>管理</span>
    </button>
    <button @click="showSetting()">
      <img src="../assets/images/setting.png">
      <span>设置</span>
    </button>
  </div>
</template>
<script>
export default {
  methods: {
    showCreate() {
      this.$emit('on-command', 'create');
    },
    showSetting() {
      this.$emit('on-command', 'setting');
    },
    toggleEditMode() {
      this.$emit('on-command', 'edit');
    }
  }
};
</script>
<style lang="less" scoped>
</style>

// src/components/newtab/TopBar.jsx
import React from "react";
import ReactDom from "react-dom";

// 顶部组件
class TopBar extends React.Component {
  constructor() {
    super();
  }
  render() {
    return (
      <div class="container-fluid">
        <div class="row">
          <div class="col control">
            <button id="new_button" data-toggle="modal" data-target="#myModal">
              <img src="./images/add.png" />
              <span>新增1114444</span>
            </button>
            <button id="edit_button">
              <img src="./images/edit.png" />
              <span>管理</span>
            </button>
            <button id="setting_button">
              <img src="./images/setting.png" />
              <span>设置</span>
            </button>
          </div>
        </div>
      </div>
    );
  }
}

module.exports = TopBar;
